// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'task.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_Task _$TaskFromJson(Map<String, dynamic> json) => _Task(
  id: _intFromJson(json['id']),
  workContent: _stringOrNullFromJson(json['work_content']),
  status: _stringOrNullFromJson(json['status']),
  statusDisplay: _stringOrNullFromJson(json['status_display']),
  taskType: _stringOrNullFromJson(json['task_type']),
  taskTypeDisplay: _stringOrNullFromJson(json['task_type_display']),
  assignedDepartmentId: _intOrNullFromJson(json['assigned_department']),
  assignedDepartmentName: _stringOrNullFromJson(
    json['assigned_department_name'],
  ),
  assignedOperatorId: _intOrNullFromJson(json['assigned_operator']),
  assignedOperatorName: _stringOrNullFromJson(json['assigned_operator_name']),
  productionQuantity: _doubleOrNullFromJson(json['production_quantity']),
  quantityCompleted: _doubleOrNullFromJson(json['quantity_completed']),
  quantityDefective: _doubleOrNullFromJson(json['quantity_defective']),
  autoCalculateQuantity: _boolOrNullFromJson(json['auto_calculate_quantity']),
  productionRequirements: _stringOrNullFromJson(
    json['production_requirements'],
  ),
  materialPurchaseStatus: _stringOrNullFromJson(
    json['material_purchase_status'],
  ),
  isDraft: _boolOrNullFromJson(json['is_draft']),
  isSubtask: _boolOrNullFromJson(json['is_subtask']),
  subtasksCount: _intOrNullFromJson(json['subtasks_count']),
  parentTaskId: _intOrNullFromJson(json['parent_task_id']),
  version: _intOrNullFromJson(json['version']),
  artworkCode: _stringOrNullFromJson(json['artwork_code']),
  artworkName: _stringOrNullFromJson(json['artwork_name']),
  dieCode: _stringOrNullFromJson(json['die_code']),
  dieName: _stringOrNullFromJson(json['die_name']),
  productCode: _stringOrNullFromJson(json['product_code']),
  productName: _stringOrNullFromJson(json['product_name']),
  materialCode: _stringOrNullFromJson(json['material_code']),
  materialName: _stringOrNullFromJson(json['material_name']),
  foilingPlateCode: _stringOrNullFromJson(json['foiling_plate_code']),
  foilingPlateName: _stringOrNullFromJson(json['foiling_plate_name']),
  embossingPlateCode: _stringOrNullFromJson(json['embossing_plate_code']),
  embossingPlateName: _stringOrNullFromJson(json['embossing_plate_name']),
  workOrderId: _intOrNullFromJson(_readWorkOrderId(json, 'work_order_id')),
  workOrderNumber: _stringOrNullFromJson(
    _readWorkOrderNumber(json, 'work_order_number'),
  ),
  customerName: _stringOrNullFromJson(_readCustomerName(json, 'customer_name')),
  processName: _stringOrNullFromJson(_readProcessName(json, 'process_name')),
  processId: _intOrNullFromJson(_readProcessId(json, 'process_id')),
  priorityDisplay: _stringOrNullFromJson(
    _readPriorityDisplay(json, 'priority_display'),
  ),
  deliveryDate: _dateTimeOrNullFromJson(
    _readDeliveryDate(json, 'delivery_date'),
  ),
  createdAt: _dateTimeOrNullFromJson(json['created_at']),
  updatedAt: _dateTimeOrNullFromJson(json['updated_at']),
);

Map<String, dynamic> _$TaskToJson(_Task instance) => <String, dynamic>{
  'id': instance.id,
  'work_content': instance.workContent,
  'status': instance.status,
  'status_display': instance.statusDisplay,
  'task_type': instance.taskType,
  'task_type_display': instance.taskTypeDisplay,
  'assigned_department': instance.assignedDepartmentId,
  'assigned_department_name': instance.assignedDepartmentName,
  'assigned_operator': instance.assignedOperatorId,
  'assigned_operator_name': instance.assignedOperatorName,
  'production_quantity': instance.productionQuantity,
  'quantity_completed': instance.quantityCompleted,
  'quantity_defective': instance.quantityDefective,
  'auto_calculate_quantity': instance.autoCalculateQuantity,
  'production_requirements': instance.productionRequirements,
  'material_purchase_status': instance.materialPurchaseStatus,
  'is_draft': instance.isDraft,
  'is_subtask': instance.isSubtask,
  'subtasks_count': instance.subtasksCount,
  'parent_task_id': instance.parentTaskId,
  'version': instance.version,
  'artwork_code': instance.artworkCode,
  'artwork_name': instance.artworkName,
  'die_code': instance.dieCode,
  'die_name': instance.dieName,
  'product_code': instance.productCode,
  'product_name': instance.productName,
  'material_code': instance.materialCode,
  'material_name': instance.materialName,
  'foiling_plate_code': instance.foilingPlateCode,
  'foiling_plate_name': instance.foilingPlateName,
  'embossing_plate_code': instance.embossingPlateCode,
  'embossing_plate_name': instance.embossingPlateName,
  'work_order_id': instance.workOrderId,
  'work_order_number': instance.workOrderNumber,
  'customer_name': instance.customerName,
  'process_name': instance.processName,
  'process_id': instance.processId,
  'priority_display': instance.priorityDisplay,
  'delivery_date': instance.deliveryDate?.toIso8601String(),
  'created_at': instance.createdAt?.toIso8601String(),
  'updated_at': instance.updatedAt?.toIso8601String(),
};
